export const contentWrapping: string;
export const cardWrapping: string;
export const primaryOutlineButton: string;
export const table: string;
export const container: string;
export const wrapper: string;
export const listWrapper: string;
export const listTitle: string;
export const divider: string;
