export const contentWrapping: string;
export const cardWrapping: string;
export const primaryOutlineButton: string;
export const table: string;
export const wrapper: string;
export const button: string;
export const google: string;
export const naver: string;
export const icon: string;
