export const contentWrapping: string;
export const cardWrapping: string;
export const primaryOutlineButton: string;
export const table: string;
export const item: string;
export const message: string;
export const time: string;
export const username: string;
export const by: string;
