export const contentWrapping: string;
export const cardWrapping: string;
export const primaryOutlineButton: string;
export const table: string;
export const sidebar: string;
export const menuContainer: string;
export const menuItem: string;
export const active: string;
export const languageSelectBox: string;
